### ISSUE TITLE
'Custom Network Example' File does not open 

### ISSUE THREAD

**Issue by JohnHadish** [NIB-SI/DiNAR#1]
When downloaded, the example Arabidopsis data (Ath GSE56094 experimental data, downloaded from left side of page here: https://nib-si.shinyapps.io/DiNAR/) can be extracted and viewed. The example network ('Custom Network Example', downloaded name 'STRINGpr1.rar'), however, cannot be extracted for viewing or use in DiNAR.

Is this file in a special format, or is it in the format listed on your website here? : 
https://nib-si.shinyapps.io/clustering/

I am using Ubuntu 18.04, error received when trying to extract is:
```
An error occurred while loading the archive.
p4
```

Thank you

**Comment by zagorGit** [comment]
Hi John!

* all data files used in DiNAR are tab-separated values format text files (*.tsv* or *.txt* extension)
* *Download example set* contains .tsv files archived in *.rar* file format 

* copy link address while using shinyapp [https://nib-si.shinyapps.io/DiNAR/ gives https://github.com/NIB-SI/DiNAR/blob/master/subApps/clustering/examples/Ath-PR1-fromSTRINGdb/STRINGpr1.rar?raw=true](https://nib-si.shinyapps.io/DiNAR/ gives https://github.com/NIB-SI/DiNAR/blob/master/subApps/clustering/examples/Ath-PR1-fromSTRINGdb/STRINGpr1.rar?raw=true)
   using `wget` and `unrar x -r STRINGpr1.rar?raw=true` two files, _STRING_PR1_EDGES_clustered.tsv_ and _STRING_PR1_NODES_clustered.tsv_, are extracted;
   which are, identical to files _STRING_PR1_EDGES_clustered.tsv_ and _STRING_PR1_NODES_clustered.tsv_ at [https://github.com/NIB-SI/DiNAR/tree/master/subApps/clustering/examples/Ath-PR1-fromSTRINGdb](https://github.com/NIB-SI/DiNAR/tree/master/subApps/clustering/examples/Ath-PR1-fromSTRINGdb)
* using 'mouse click', it downloads _STRINGpr1.rar_ file; then again `unrar` extracts successfully both files

* In addition, in DiNAR shiny app, while _browsing_ for network files to upload, switch from _Custom files_ to _All files_ option to see .tsv extension and upload _STRING_PR1_NODES_clustered.tsv_ followed by _STRING_PR1_EDGES_clustered.tsv_

Tested 2019-01-24 on Linux Mint 18.2 "Sonya" - Cinnamon (64-bit) 4.13.0-41

Let us know if it worked.
